apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backplane-must-gather-cr7q
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/backplane-must-gather/backplane-must-gather-cr7q@sha256:501972a9e597aea0dcb244cecbbdbec6557f2df92c7dcdf7a78defaab32b8831
        name: container-image
        resources: {}
status: {}
