apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backplane-must-gather-cr7q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/backplane-must-gather/backplane-must-gather-cr7q@sha256:ff74b742566f04c29aaf538de5214d281f8c3889a6b619ac49adb2347ab8f352
        name: container-image
        resources: {}
status: {}
