apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backplane-must-gather-cr7q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backplane-must-gather-cr7q
    app.kubernetes.io/part-of: backplane-must-gather
  name: backplane-must-gather-cr7kfxh
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backplane-must-gather-cr7q
    weight: 100
status: {}
