apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backplane-must-gather-cr7q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backplane-must-gather-cr7q
    app.kubernetes.io/part-of: backplane-must-gather
  name: backplane-must-gather-cr7q
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: backplane-must-gather-cr7q
status:
  loadBalancer: {}
